version: "3.9"

services: 
    users:
        build: 
            context: .
            target: dev
        command: npm run dev:users
    gateway:
        build:
            context: .
        ports: 
            - 3000:3000
        depends_on: 
            - users